server:
  port: 10712
  ip: 60.205.1.134

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/advertisement?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#spring:
#  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://localhost:3306/advertisement?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource

param:
  token: lixiaosaoailuxiaoxian1314
  appid: wx1a8659b5d7d8ce06
  secret: 0f84cbd97c00130619226927d1bbca65
  width: 500
  height: 500